### ISSUE TITLE
DotNet Core Support

### ISSUE THREAD

**Issue by jbrule** [kaltura/clients-generator#331]
I am wanting to use the .NET client on a dotnetcore 2.0 app. However the library available on the [Native Client libraries page](https://developer.kaltura.com/api-docs/Client_Libraries) does not appear to support it. The posted libraries are in fact over a year old (http://cdnbakmi.kaltura.com/content/clientlibs/csharp_02-10-2017.tar.gz). I see [netstandard 2.0 was merged back in Feb 2018](https://github.com/kaltura/clients-generator/pull/272). I understand that I can install the whole Kaltura server stack and run client-generator, however that seems like quite a task. When will the the posted libraries be updated.

**Comment by jessp01** [comment]
Hi @jbrule,

A pre-generated C# client can always be obtained from:
https://github.com/kaltura/KalturaGeneratedAPIClientsCsharp

Note that we have a nightly CI process running against the master branch and I'd advise against using it on production. However, you can clone the repo and use the stable 13.20.0 branch [or download the ZIP for it].

You may also use http://cdnbakmi.kaltura.com/content/clientlibs/csharp_26-04-2018.tar.gz.

We're now at work on a new version of developer.kaltura.com and will be going live with it shortly. At which point, the client download links will also be updated.

Thanks,

**Comment by jbrule** [comment]
Thank you I will try the repo. I am getting a 404 @ http://cdnbakmi.kaltura.com/content/clientlibs/csharp_26-04-2018.tar.gz

**Comment by jessp01** [comment]
Hi @jbrule - yes, I get HTTP 404 for that one as well. My apologies. I'll have the right person look into that.
For now, please clone the repo or use https://github.com/kaltura/KalturaGeneratedAPIClientsCsharp/archive/13.20.0.zip

Thanks for reporting and do let me know should you have additional issues,
